export const LOCAL_FRIDGE_DB = {
  potato: [
    "Did you know that potatoes were the very first vegetable to be successfully grown in microgravity in space back in 1995?",
    "Potatoes originated in the Andes Mountains of South America and were first domesticated over 7,000 years ago.",
    "Potatoes are one of the world's most important food crops, after maize, wheat, and rice.",
    "Potatoes are an excellent source of vitamin C, vitamin B6, and potassium, especially when eaten with the skin.",
    "In 19th-century Alaska during the Klondike gold rush, potatoes were so highly valued for their Vitamin C content that miners traded gold for them.",
      ],
  tomato: [
    "Tomatoes are botanically fruits (berries), although they are commonly used as vegetables in cooking.",
    "Tomatoes originated in western South America and were first cultivated in present-day Mexico.",
    "Tomatoes are rich in lycopene, a powerful antioxidant associated with heart health and reduced risk of certain diseases.",
    "There are over 10,000 cultivated varieties of tomatoes, including cherry, plum, beefsteak, and heirloom tomatoes.",
    "Tomatoes are about 95% water, making them low in calories while providing vitamins A, C, and K.",
      ],
  onion: [
    "Onions have been cultivated for at least 5,000 years and are among the oldest cultivated vegetables.",
    "Cutting onions releases sulfur-containing compounds that irritate the eyes and cause tears.",
    "Onions belong to the same plant family as garlic, leeks, shallots, and chives.",
    "Onions are a good source of vitamin C, fiber, and antioxidants such as quercetin.",
    "Onions come in several common types, including yellow, red, and white, each with distinct flavors and culinary uses.",
      ],
  carrot: [
    "The earliest cultivated carrots were purple and yellow; orange carrots became popular in the Netherlands during the 16th century.",
    "Carrots are rich in beta-carotene, which the body converts into vitamin A.",
    "Carrots contain fiber and antioxidants and are naturally sweet because they store sugars in their roots.",
    "Carrots can be eaten raw, roasted, steamed, boiled, pickled, or used in cakes and desserts.",
    "Carrots grow best in cool weather. They develop their sweetest flavor when grown in cooler temperatures because the plant converts starch into natural sugars."
      ],
  cabbage: [
    "Cabbage has been cultivated in Europe for more than 2,000 years.",
    "Cabbage belongs to the same species as broccoli, cauliflower, Brussels sprouts, and kale.",
    "Cabbage is an excellent source of vitamin C, vitamin K, and dietary fiber.",
    "Cabbage can be eaten fresh, cooked, or fermented into foods such as sauerkraut and kimchi.",
    "Green, red (purple), and Savoy cabbage are the most common varieties, each with slightly different textures and flavors.",
      ],
  lettuce: [
    "Lettuce is one of the oldest cultivated leafy vegetables, grown for over 2,500 years.",
    "Lettuce is about 95% water, making it a very hydrating food.",
    "Darker green varieties of lettuce generally contain more vitamins and minerals than lighter varieties",
    "Lettuce grows best in cool weather and can become bitter in hot temperatures.",
      ],
  cucumber: [
    "Cucumbers are about 96% water, making them one of the most water-rich vegetables.",
    "Cucumbers originated in India over 3,000 years ago.",
    "Cucumbers belong to the same plant family as pumpkins, melons, and squash.",      
    "Cucumbers are low in calories while providing vitamin K and antioxidants.",
      ],
  bell_pepper: [
    "Bell peppers come in green, red, yellow, orange, purple, and even white varieties.",
    "Red bell peppers contain much more vitamin C than oranges, gram for gram.",
    "Green peppers are simply unripe versions of most red, yellow, or orange peppers.",
    "Bell peppers are the only common peppers that contain no capsaicin, so they are not spicy.",
    "Bell peppers are rich in vitamins A, C, and several antioxidants.",
    ],    
  broccoli: [
    "Broccoli belongs to the same species as cabbage, cauliflower, kale, and Brussels sprouts.",
    "Broccoli is an excellent source of vitamins C and K.",
    "The part of broccoli that we eat is actually a cluster of unopened flower buds.",
    "Broccoli was first developed in Italy more than 2,000 years ago.",
    "Both the florets and stems of broccoli are edible and nutritious.",
    ],
  cauliflower:[
    "Cauliflower is made up of tightly packed, undeveloped flower buds.",
    "Cauliflower comes in white, purple, orange, and green varieties.",
    "Cauliflower is naturally high in vitamin C and fiber.",
    "Cauliflower can be mashed, roasted, steamed, or used as a low-carb rice substitute.",
    "Cauliflower belongs to the same species as broccoli, cabbage, and kale.",
    ],
  spinach: [
    "Spinach originated in ancient Persia (modern-day Iran).",
    "Spinach is rich in iron, folate, vitamins A, C, and K.",
    "Spinach grows best in cool weather and matures quickly.",
    "Spinach can be eaten raw in salads or cooked in soups, pasta, and other dishes",
    ],
  courgette : [
    "Zucchini is a type of summer squash.",
    "Zucchini is harvested while still immature, making it tender and mild in flavor.",
    "Zucchini flowers are edible and are considered a delicacy in many countries.",
    "Zucchini contains vitamins C and B6 as well as potassium.",
    "A single zucchini plant can produce many fruits throughout the growing season.",
    ],
  eggplant: [
    "Although it is cooked like a vegetable, eggplant is technically a berry because it develops from a flower and contains many small edible seeds.",
    "Eggplants are closely related to tomatoes, potatoes, and bell peppers, all of which belong to the nightshade family.",
    "Eggplant skin contains nasunin, an antioxidant that gives purple eggplants their color and helps protect plant cells from damage.",
    "Their soft, sponge-like flesh readily soaks up herbs, spices, sauces, and oils, making them a key ingredient in dishes such as moussaka, ratatouille, eggplant Parmesan, and baba ghanoush.",  
  ],
  avocado: [
      "Avocados are classified as a large berry because they develop from a flower and contain a single large seed.",
      "Avocados are high in monounsaturated fats, particularly oleic acid, which is the same heart-healthy fat found in olive oil.",
      "A medium avocado provides around 700 mg of potassium, which helps support healthy muscles, nerves, and blood pressure.",
      "Avocados are harvested while firm and mature. They soften over several days at room temperature, and placing them in a paper bag with a banana or apple can speed up the ripening process because of the ethylene gas those fruits release.",
      "Avocados are a good source of fiber, vitamins K, C, E, and several B vitamins, making them one of the most nutrient-dense fruits available.",
    ],
  banana: [
    "Bananas are one of the world's most popular fruits and are available year-round.",
    "Bananas are rich in potassium, vitamin B6, and vitamin C.",
    "Bananas grow in large clusters on giant herbaceous plants, not trees.",
    "Bananas are picked while still green and ripen during transport.",
    "Bananas provide natural carbohydrates, making them a popular snack before exercise.",
    ],
  apple: [
    "Apples have been cultivated for thousands of years and originated in Central Asia.",
    "There are over 7,500 varieties of apples grown around the world.",
    "Apples are high in fiber, especially when eaten with the skin.",
    "Apples contain vitamin C and antioxidants called polyphenols.",
    ],
  orange: [
    "Oranges are one of the best-known sources of vitamin C.",
    "Sweet oranges are believed to have originated in China.",
    "Oranges are about 90% water, making them refreshing and hydrating.",
    "Orange peels contain fragrant oils used in perfumes and cooking.",
  ],
  grape: [
  "Grapes have been cultivated for more than 8,000 years.",
  "Grapes grow in clusters on woody vines.",
  "Grapes come in green, red, black, and purple varieties.",
  "Grapes are rich in antioxidants, including resveratrol, which is found mainly in the skins of red and purple grapes.",
  ],
  strawberry: [
   "Strawberries are the only fruit with their seeds on the outside.",
  "An average strawberry has around 200 seeds.",  
  "Strawberries are an excellent source of vitamin C and manganese.",
  "Strawberries belong to the rose family.", 
  ],
  mandarin: [
  "Mandarins are smaller and sweeter than most oranges.",
  "Mandarins are rich in vitamin C and vitamin A.",
  "Mandarins are especially popular during the autumn and winter months.",
  "Clementines, satsumas, and tangerines are all types of mandarins.",
  ],
  pear: [
  "Pear trees can produce fruit for 50 years or more.",
  "Pears are a good source of fiber and vitamin C.",
  "Unlike many fruits, pears ripen best after they are picked.",
  "Pears come in many varieties, including Bartlett, Conference, and Bosc.",
  ],
  peach: [
  "Peaches originated in China more than 4,000 years ago.",
  "Peaches are rich in vitamins A and C.",
  "Peaches can have either fuzzy skin or smooth skin (nectarines).",
  "The flesh of a peach may be white or yellow depending on the variety.",
  ],
  watermelon: [
  "Watermelons are about 92% water.",
  "Watermelons originated in Africa and have been cultivated for thousands of years.",
  "Watermelon is rich in vitamins A and C.",
  "The red color of a watermelon comes from the antioxidant lycopene.",
  "Nearly every part of a watermelon is edible, including the rind and seeds.",
  ],  
  kiwi: [
  "Kiwi originated in China but was later widely cultivated in New Zealand.",
  "Kiwi contains more vitamin C per serving than many citrus fruits.",
  "Gold kiwi varieties are sweeter than traditional green ones.",
  "Kiwi is also a good source of fiber, vitamin K, and potassium.",
  ],
  lemon: [
  "Lemons are famous for their high vitamin C content.",
  "Lemons are thought to have originated in Asia.",
  "Lemon juice is highly acidic because it contains citric acid.",
  "Both the juice and the peel of lemons are widely used in cooking and baking.",
  ],
  blueberry: [
  "Blueberries are rich in antioxidants called anthocyanins, which give them their blue color.",
  "Blueberries are an excellent source of vitamin C, vitamin K, and fiber.",
  "Blueberries grow on shrubs and are native to North America, although they are now widely grown in Europe.",
  "Blueberries are one of the few fruits that naturally have a dusty blue protective coating called a bloom, which helps keep the fruit fresh.",
  ],
  bread: [
  "Bread has been a staple food for more than 10,000 years.",
  "Wholegrain bread contains more fiber than white bread.",
  "Bread can be frozen and thawed with little loss of quality.",
  ],
  eggs: [
    "Fresh eggs sink in water, while older eggs float because of a growing air pocket inside.",
    "Eggshells are porous and can have up to 17,000 tiny pores, allowing them to absorb strong odors if stored next to smelly food.",
    "An average chicken lays about 250 to 300 eggs per year, taking roughly 24 to 26 hours to produce a single egg.",
    "The chef's hat (toque) traditionally has exactly 100 folds, which historically represented the 100 different ways a master chef knows how to cook an egg.",
  ],
  cheese:[
    "There are over 2,000 varieties of cheese worldwide.",
    "Hard cheeses generally keep longer than soft cheeses.",
    "Cheese is rich in calcium and protein.",
  ],
  butter: [
    "Butter is made by churning cream until the fat separates.",
    "Butter has been made for thousands of years.",
    "Unsalted butter is often preferred for baking because it allows better control of seasoning.",
  ],
  yogurt: [
    "Did you know that the word 'yogurt' comes from a Turkish word meaning 'to curdle or thicken'?",
    "Yogurt has been a part of the human diet for over 5,000 years, originating in Central Asia.",
    "The lactic acid in yogurt helps break down lactose, making it easier to digest for some lactose-intolerant people.",
  ],
  rice: [
    "Rice feeds more than half of the world's population.",
    "Rice is naturally gluten-free.",
    "Every grain of white rice started as brown rice. White rice has the bran removed, while brown rice keeps it.",
  ],

};
